version: '2'
services:
  saltmaster:
    hostname: saltmaster
    privileged: true
    cap_add:
      - SYS_ADMIN
    environment:
      container: docker
    command: /usr/sbin/init
    build:
      context: saltstack/master/
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./saltstack/salt:/srv/salt
      - ./saltstack/pillar:/srv/pillar
    networks:
      - salt
  minion1:
    hostname: minion1
    privileged: true
    cap_add:
      - SYS_ADMIN
    environment:
      container: docker
    command: /usr/sbin/init
    build:
      context: saltstack/minion1/
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - salt
  minion2:
    hostname: minion2
    privileged: true
    cap_add:
      - SYS_ADMIN
    environment:
      container: docker
    command: /usr/sbin/init
    build:
      context: saltstack/minion2/
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - salt
  zoo1:
    image: zookeeper
    restart: always
    ports:
        - 2181:2181
    environment:
        ZOO_MY_ID: 1
        ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - salt
  zoo2:
    image: zookeeper
    restart: always
    ports:
        - 2182:2181
    environment:
        ZOO_MY_ID: 2
        ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - salt
  zoo3:
    image: zookeeper
    restart: always
    ports:
        - 2183:2181
    environment:
        ZOO_MY_ID: 3
        ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - salt
networks:
  salt:
