version: '2'
services:
  salt:
    hostname: salt
    privileged: true
    cap_add:
      - SYS_ADMIN
    environment:
      container: docker
    command: /usr/sbin/init
    build:
      context: saltstack/master/
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./saltstack/salt:/srv/salt
      - ./saltstack/pillar:/srv/pillar
    networks:
      - salt
    ports:
      - 8000:8000
  minion:
    privileged: true
    cap_add:
      - SYS_ADMIN
    environment:
      container: docker
    command: /usr/sbin/init
    build:
      context: saltstack/minion/
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - salt
    dns:
      - 8.8.8.8
networks:
  salt:
